### ISSUE TITLE
Support localisations for non-English languages (L10n)

### ISSUE THREAD

**Issue by cvan** [Pinecast/www#20]
I've used [webL10n](https://github.com/fabi1cazenave/webL10n) with great success in the past.

https://github.com/mozilla/moz-games/blob/642790f/public/gdc/index.html#L13-L14
https://github.com/mozilla/moz-games/blob/642790f/public/gdc/l10n/locales.ini
https://github.com/mozilla/moz-games/blob/642790f3/public/gdc/js/l10n.js
https://github.com/mozilla/moz-games/blob/642790f/public/gdc/js/main.js#L21-L25

webL10n doesn't seem be actively maintained. I wonder if there's anything better out there these days. I know for the `Pinecast/pinecast` repo you're using server-side l10n with Django. I assume you don't want to add too much complexity to the `www` front-end site.

**Comment by mattbasta** [comment]
Honestly, I'd rather rebuild the site to use a proper CMS than translate it otherwise.

The other problem is that translating the marketing site doesn't help much because--though the app has L10n support--I haven't translated it. On top of that, I can't do sales or support in other languages either. By the time I could get resources together, I'll have outgrown what's currently in this repo.

It's also worth noting that the tools that most podcasters use aren't well-translated anyway. Here's Audacity in French:

<img width="961" alt="screen shot 2016-09-20 at 8 34 57 pm" src="https://cloud.githubusercontent.com/assets/279498/18696945/cf9e6a94-7f71-11e6-9910-1a751b24aacf.png">

French is one of the better languages, and you can see there's still plenty of English strings hanging out. Here's GarageBand in French:

<img width="1652" alt="screen shot 2016-09-20 at 8 38 53 pm" src="https://cloud.githubusercontent.com/assets/279498/18696995/527ed87c-7f72-11e6-9059-1d8fcd5091c6.png">

Equally bad, if not worse in some cases.

This isn't to say I want to snub non-English-speaking podcasters, but there's simply a smaller market that I could target anyway even if I did have the resources to translate and support a localized app. As pinecast-studio progresses, though, I'll revisit this.

**Comment by cvan** [comment]
gotcha, and wow - it must be hard for non-English-speaking podcasters
